### student details
Name: Vijayanagara Sharanya
regno: 21bce8002
campus: VIT-AP

### Numpy exercises 

In [2]:
import numpy as np

#### array of 10 zeroes


In [4]:

a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### array of 10 ones

In [5]:

b = np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### array of 10 fives

In [10]:

c = np.ones(10) *5
c

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [16]:

d = np.arange(10,50)
d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Create an array of all the even integers from 10 to 50

In [18]:

e = np.arange(10,50,2)
e

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [19]:

f = np.array([[[0,1,2],[3,4,5],[6,7,8]]])
f

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

#### Create a 3x3 identity matrix

In [21]:

g = np.eye(3)
g

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [38]:

h = np.random.rand()
h

0.4321769942291821

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [39]:

i = np.random.normal(size=25)
i

array([ 0.07246378, -0.03125076,  1.57649894,  0.98313825, -0.82044295,
        0.21222587,  0.71672304,  0.33594553,  1.69292581, -0.71717881,
       -0.65662545,  1.35989328, -0.51880077,  2.92444205, -0.33026765,
       -0.64496267, -2.20886565, -0.09955135, -0.69008888, -0.24121851,
        0.28093056, -0.64002403, -1.10084203,  0.05794563,  0.10472528])

#### Create the following matrix

In [42]:
j = np.linspace(0.01,1,100)
j

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

#### Create an array of 20 linearly spaced points between 0 and 1

In [47]:

k = np.linspace(0,1,20)
k

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

### Numpy Indexing and Selection



In [48]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### print the following output
#### array([[12, 13, 14, 15],
####        [17, 18, 19, 20],
####        [22, 23, 24, 25]])

In [65]:

p = mat[2:5,1:5]
p

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### get the number 20

In [72]:

q = mat[3,4]
q

20

#### get this output
#### array([[ 2],
####       [ 7],
####       [12]])

In [85]:

r = mat[1:4,1:2]
r

array([[ 7],
       [12],
       [17]])

#### get this output
array([21, 22, 23, 24, 25])

In [90]:

s = mat[4:5]
s

array([[21, 22, 23, 24, 25]])

#### get this output
#### array([[16, 17, 18, 19, 20],
####        [21, 22, 23, 24, 25]])

In [91]:

t = mat[3:5]
t

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# Now do the following

#### Get the sum of all the values in mat

In [92]:

l = mat.sum()
l

325

#### Get the standard deviation of the values in mat

In [94]:

m = mat.std()
m

7.211102550927978

#### Get the sum of all the columns in mat

In [96]:

n = np.sum(mat, axis=0)
n

array([55, 60, 65, 70, 75])